name:         mathbox
version:      0.0.0
author:       Herman Bergwerf <hermanbergwerf@gmail.com>
description:  Dart wrapper for MathBox
homepage:     https://github.com/eqdb/mathbox
environment:
  sdk:        '>=1.8.0 <2.0.0'
dependencies:
